name: flutter_meditation_app
description: A new Flutter project.


publish_to: 'none' 

environment:
  sdk: ">=2.7.0-80.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.1
  audioplayers: ^0.20.1
  cached_network_image: ^3.2.0
  fluttertoast: ^8.0.8
  firebase: ^9.0.2
  firebase_auth: ^3.3.7
  firebase_core: ^1.12.0
  firebase_database: ^9.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - images/
    - assets/

